export const ADD_COUNTRIES = "ADD_COUNTRIES";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const CLEAN_COUNTRY_DETAIL = "CLEAN_COUNTRY_DETAIL"; 
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const RESET_COUNTRIES = "RESET_COUNTRIES";